site_name: A brief Language Tutorial
site_url: https://clarelab.github.io/lang-tutorial

repo_name: lang-tutorial
repo_url: https://github.com/clareLab/lang-tutorial

theme:
  name: material
  # custom_dir: docs/overrides
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/icon.svg
  favicon: assets/icon.svg
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

extra:
  social:
    - icon: fontawesome/solid/user
      link: https://clarelab.github.io
    - icon: fontawesome/brands/github
      link: https://github.com/clareLab
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@clareLa6
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/453838432
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/c1areLab
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/user/No-Lab4175
    # - icon: fontawesome/solid/blog
    #   link: https://clarelab.hatenablog.com
    # - icon: fontawesome/brands/itch-io
    #   link: https://clarelab.itch.io

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
          - name: math
            class: arithmatex
            format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true

plugins:
  - awesome-pages
  - exclude:
      glob:
        - src/*
  - git-authors:
      show_contribution: true
      show_line_count: true
  - git-revision-date-localized:
      fallback_to_build_date: true
  - include-markdown
  - mkdocs-ja-ruby
  - search

nav:
  - Home:
    - index.md