site_name: A brief Language Tutorial
site_url: https://clarelab.github.io/lang-tutorial

repo_name: lang-tutorial
repo_url: https://github.com/clareLab/lang-tutorial

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/icon.png
  favicon: assets/icon.png
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

extra:
  social:
    - icon: fontawesome/solid/user
      link: https://clarelab.github.io
    - icon: fontawesome/brands/github
      link: https://github.com/clareLab
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@clareLa6
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/453838432
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/c1areLab
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/user/No-Lab4175
    # - icon: fontawesome/solid/blog
    #   link: https://clarelab.hatenablog.com
    # - icon: fontawesome/brands/itch-io
    #   link: https://clarelab.itch.io

# Markdown features
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - md_in_html
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

# Plugins
plugins:
  - awesome-pages
  - exclude:
      glob:
        - src/*
  - include-markdown
  - search

nav:
  - Home:
    - index.md